name: pre-commit hooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout rush
      uses: actions/checkout@v2

    - name: set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit


    - name: run pre-commit hooks
      run: |
        pre-commit run --all-files
